# This workflow push (create/update) a configuration to a Solace PubSub+ event broker
name: PushConfig

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - config/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          # https://stackoverflow.com/questions/69369569/capturing-git-command-output-in-github-actions
          fetch-depth: 5

      - name: Download Solconfig jar
        run: curl -LJO https://github.com/swayvil/solconfig/releases/tag/v1.1.7.1/solconfig.jar

      - name: Get pushed file
        id: step_one
        run: |
            echo "FILE=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | head -2 | tail -1)" >> $GITHUB_ENV
 
      - name: Display pushed file
        id: step_two
        run: |
            echo "${{ env.FILE }}"
        
      - name: Push config
        env:
          SEMP_URL: ${{ vars.SEMP_URL }}
          SEMP_USER: ${{ vars.SEMP_USER }}
          SEMP_PWD: ${{ secrets.SEMP_PWD }}
        run: java -jar solconfig.jar -H=${SEMP_URL} -u=${SEMP_USER} -p=${SEMP_PWD} update --no-delete --skip-vpn ${{ env.FILE }}
